version: '2'

services:
  rio-auth:
    image: rio-catalog
    restart: always
    ports:
      - 3000:3000
    links:
      - mongo
    command:
      --MONGO_URI=mongodb://mongo:27017/rio-catalog
      --ISSUER=me
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
